spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active : docker # 기본값: 로컬 개발 (운영에서는 prod로 override)

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG

server:
  port: 8082

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}
