spring:
  datasource:
    url: jdbc:mysql://database-vote.clg8smew8hja.ap-northeast-2.rds.amazonaws.com:3306/vote?useSSL=false&serverTimezone=UTC
    username: admin
    password: vote1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG

server:
  port: 8081

