spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: prod # 기본값: 로컬 개발 (운영에서는 prod로 override)

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG

server:
  port: 8082
